# Generated by Django 2.2 on 2019-04-13 16:29

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('start_date', models.DateField(verbose_name='Дата рождения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='Отдел')),
            ],
        ),
    ]
